version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: git submodule update --init --recursive
      - run: ./gradlew clean :1.15.2:build
      - run: mkdir artifacts || true && cp versions/1.15.2/build/libs/replaymod-1.15.2-2.3.0-dirty.jar artifacts/urmw-replay-mod-1.15.2.jar

      - store_artifacts:
          path: artifacts
