version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: git submodule update --init --recursive
      - run: ./gradlew clean :1.15.2:build
      - store_artifacts:
          path: versions/1.15.2/build/libs
